### ISSUE TITLE
chroot同時安装Box86 Wine + Box64 Wine64 | Ivon's Blog

### ISSUE THREAD

**Issue by ivon852** [ivon852/ivon852.github.io#16]
https://ivon852.github.io/2022/01/21/chroot%E5%AE%89%E8%A3%85Box86-Wine-Box64-Wine64/ 

 這篇文章探討如何讓Box86與Box64共存於同一個ARM 64位元環境，這樣子就可以按情況執行32位元或者64位元的Wine + exe應用程式，甚至是同時執行。 (左邊32位元彈珠檯，右邊64位元播放器)

**Comment by ThieuMinh26** [comment]
hello what is the best vnc viewer ? , is there any linux deploy install tutorial + box 86/64+wine ?

**Comment by ThieuMinh26** [comment]
should i use ubuntu or debian / xfce or mate for better ui ? , i tried installing but the ui seem broken , i cant see icon and stuff

**Comment by ivon852** [comment]
> @ThieuMinh26
> should i use ubuntu or debian / xfce or mate for better ui ? , i tried installing but the ui seem broken , i cant see icon and stuff

I use RealVNC Viewer. XFCE is enough.

Upgrade Linux deploy Uubntu to 20.04:  https://ivon852.github.io/2022/01/19/Linux-Deploy-Ubuntu-18-04%E5%A6%82%E4%BD%95%E5%8D%87%E7%B4%9A%E8%87%B320-04/

Box64 + Box 86 compliation guide in English: https://www.reddit.com/r/termux/comments/s8qeti/box86_wine_in_64bit_chroot/

**Comment by ThieuMinh26** [comment]
ok

**Comment by ThieuMinh26** [comment]
> > @ThieuMinh26
> > should i use ubuntu or debian / xfce or mate for better ui ? , i tried installing but the ui seem broken , i cant see icon and stuff
> 
> I use RealVNC Viewer. XFCE is selected for better performance.
> 
> (Chinese) Ubuntu of Linux Deploy is old version, upgrade it to 20.04: https://ivon852.github.io/2022/01/19/Linux-Deploy-Ubuntu-18-04%E5%A6%82%E4%BD%95%E5%8D%87%E7%B4%9A%E8%87%B320-04/
> 
> (English) Box64 + Box 86 compliation guide: https://www.reddit.com/r/termux/comments/s8qeti/box86_wine_in_64bit_chroot/

have you managed to run linux deploy with virgl
