### ISSUE TITLE
Linux Deploy Ubuntu 18.04如何升級至20.04 | Ivon's Blog

### ISSUE THREAD

**Issue by ivon852** [ivon852/ivon852.github.io#17]
https://ivon852.github.io/2022/01/19/Linux-Deploy-Ubuntu-18-04%E5%A6%82%E4%BD%95%E5%8D%87%E7%B4%9A%E8%87%B320-04/ 

 在安裝Linux Deploy的Ubuntu後，會發現下載的Ubtuntu版本只到18.04，要升級到20.04有二種方法: 直接指定下載20.04，或是先裝再升級。 完成更新後，記得要停止chroot掛載再重新啟動。

**Comment by ThieuMinh26** [comment]
can you make a youtube tutorial ? i kinda not familiar with linux deploy
