### ISSUE TITLE
Android基本刷機流程 | Ivon's Blog

### ISSUE THREAD

**Issue by ivon852** [ivon852/ivon852.github.io#25]
https://ivon852.github.io/2021/12/29/Android%E5%9F%BA%E6%9C%AC%E5%88%B7%E6%A9%9F%E6%B5%81%E7%A8%8B/ 

 這篇不是某部手機的刷機教學，是我刷過幾個大廠牌(華碩、三星、小米、Sony)的手機歸納出來的刷機通用步驟。 首先要認識一些名詞，再來看刷機的流程原理。最後討論刷機的好處與壞處(如果你很在意這點，請先看最後一段)。

**Comment by wuxian3635** [comment]
在linux上可以安裝高通驅動，adb來解bootloder嗎？ 手機proot容器虛擬運行win可以以解嗎？

**Comment by ivon852** [comment]
> @wuxian3635
> 在linux上可以安裝高通驅動，adb來解bootloder嗎？ 手機proot容器虛擬運行win可以以解嗎？

對電腦Linux而言，驅動應該都是內建的。而大部分Linux發行版都有提供adb和fastboot 套件。
而解鎖手機bootloader，通常電腦問題不大。
如果你說要用Temrux這種用連線方式給另外一支手機解鎖bootloader，或許要root權限，因為Android 的USB有點複雜，有時候還會讀不到。
此外，Proot無法執行Windows，要用QEMU，但是目前非常慢。

**Comment by wuxian3635** [comment]
谢谢解答。

ivon852 ***@***.***> 于 2022年3月27日周日 19:40写道：
