### ISSUE TITLE
編譯Android Kernel遇到的error紀錄 | Ivon's Blog

### ISSUE THREAD

**Issue by ivon852** [ivon852/ivon852.github.io#30]
https://ivon852.github.io/2021/12/26/%E7%B7%A8%E8%AD%AFAndroid-Kernel%E9%81%87%E5%88%B0%E7%9A%84error%E7%B4%80%E9%8C%84/ 

 這篇文章紀錄我編譯Android kernel(內核)遇到的錯誤，大多不是深入的程式寫法的問題，只要找到正確的檔案修改一下就解決了。把問題拿去Google通常都有簡單的答案，錯誤訊息用” “框起來搜尋更有機會找到別人遇過的錯誤。

**Comment by RanceStar** [comment]
Hi Ivon大大，想請問你make時有遇到以下錯誤嗎? 我也是用Lineage OS 18, 只是我手機是htc desire eye, 有參照你先前教學，先make一次有ok，再新增CONFIG以後會卡在下面的錯誤。

  CC      kernel/pid_namespace.o
kernel/pid_namespace.c: In function 'pidns_install':
kernel/pid_namespace.c:279:21: error: 'struct pid_namespace' has no member named 'user_ns'
  if (!ns_capable(new->user_ns, CAP_SYS_ADMIN))
                     ^
make[1]: *** [scripts/Makefile.build:308: kernel/pid_namespace.o] Error 1
