### ISSUE TITLE
3D硬體加速的Proot Linux | Ivon's Blog

### ISSUE THREAD

**Issue by ivon852** [ivon852/ivon852.github.io#6]
https://ivon852.github.io/2021/12/10/3D%E7%A1%AC%E9%AB%94%E5%8A%A0%E9%80%9F%E7%9A%84Proot-Linux/ 

 一、實驗目的：在Android手機執行Linux桌面程式，自行編譯驅動，觀看1080p影片和玩3D遊戲，外接螢幕和使用鍵鼠操作。

**Comment by lalakao118** [comment]
meson编译wayland-protocol的时候，报错说/usr/bin/wayland-scanner不存在。实际这个文件是存在的，不过文件目录为/data/data/com.termux/files/usr/bin。如何处理？

**Comment by ivon852** [comment]
> @lalakao118
> meson编译wayland-protocol的时候，报错说/usr/bin/wayland-scanner不存在。实际这个文件是存在的，不过文件目录为/data/data/com.termux/files/usr/bin。如何处理？
有無更詳細的log?

**Comment by lalakao118** [comment]
有两处报错，一处在编译wayland时提示找不到nm程序，第二处就是找不到/usr/bin/wayland-scanner。麻烦大神指点迷津！

~/dir/wayland/b $ ls
config.h  cursor  egl  meson-info  meson-logs  meson-private  meson-uninstalled  src
~/dir/wayland/b $ meson -Dprefix=$PREFIX -Ddocumentation=false ..
The Meson build system
Version: 0.61.1
Source dir: /data/data/com.termux/files/home/dir/wayland
Build dir: /data/data/com.termux/files/home/dir/wayland/b
Build type: native build
Project name: wayland
Project version: 1.20.90
C compiler for the host machine: cc (clang 13.0.1 "clang version 13.0.1")
C linker for the host machine: cc ld.lld 13.0.1
Host machine cpu family: aarch64
Host machine cpu: aarch64
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Has header "sys/prctl.h" : YES 
Has header "sys/procctl.h" : NO 
Has header "sys/ucred.h" : NO 
Checking for function "accept4" : YES 
Checking for function "mkostemp" : YES 
Checking for function "posix_fallocate" : YES 
Checking for function "prctl" : YES 
Checking for function "memfd_create" : NO 
Checking for function "mremap" : YES 
Checking for function "strndup" : YES 
Checking whether type "struct xucred" has member "cr_pid" : NO 
Found pkg-config: /data/data/com.termux/files/usr/bin/pkg-config (0.29.2)
Run-time dependency libffi found: YES 3.4.2
Header <sys/signalfd.h> has symbol "SFD_CLOEXEC" : YES 
Header <sys/timerfd.h> has symbol "TFD_CLOEXEC" : YES 
Header <time.h> has symbol "CLOCK_MONOTONIC" : YES 
Checking for function "clock_gettime" : YES 
Configuring config.h using configuration
Configuring wayland-version.h using configuration
Run-time dependency expat found: YES 2.4.4
Run-time dependency libxml-2.0 found: YES 2.9.12
Program embed.py found: YES (/data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/home/dir/wayland/src/embed.py)
Library m found: YES
Run-time dependency threads found: YES
Program nm found: NO

../egl/meson.build:14:0: ERROR: Program 'nm' not found or not executable

A full log can be found at /data/data/com.termux/files/home/dir/wayland/b/meson-logs/meson-log.txt
~/dir/wayland/b $ cd ~/dir/wayland-protocols
~/dir/wayland-protocols $ meson -Dprefix=$PREFIX ..
The Meson build system
Version: 0.61.1
Source dir: /data/data/com.termux/files/home/dir/wayland-protocols
Build dir: /data/data/com.termux/files/home/dir
Build type: native build
Project name: wayland-protocols
Project version: 1.25
Host machine cpu family: aarch64
Host machine cpu: aarch64
Configuring wayland-protocols.pc using configuration
Configuring wayland-protocols-uninstalled.pc using configuration
Program scan.sh found: YES (/data/data/com.termux/files/home/dir/wayland-protocols/tests/scan.sh)
Found pkg-config: /data/data/com.termux/files/usr/bin/pkg-config (0.29.2)
Build-time dependency wayland-scanner found: YES 1.17.0
Program /usr/bin/wayland-scanner found: NO

tests/meson.build:3:0: ERROR: Program '/usr/bin/wayland-scanner' not found or not executable

A full log can be found at /data/data/com.termux/files/home/dir/meson-logs/meson-log.txt
~/dir/wayland-protocols $ which wayland-scanner
/data/data/com.termux/files/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/data/data/com.termux/files/usr/bin/wayland-scanner
~/dir/wayland-protocols $ ^C
~/dir/wayland-protocols $

**Comment by ivon852** [comment]
要不要試試換個meson版本
pip install meson==0.60.0

**Comment by lalakao118** [comment]
感谢！已解决。
安装binutils包：pkg install binutils，之后解决了找不到nm程序的问题。
wayland-scanner找不到和libwayland*包的安装有关。

**Comment by zhangjing-GitHub-Code** [comment]
> @lalakao118
> meson编译wayland-protocol的时候，报错说/usr/bin/wayland-scanner不存在。实际这个文件是存在的，不过文件目录为/data/data/com.termux/files/usr/bin。如何处理？

可以termux-chroot(不过可能要安装proot和termux-tools什么的)

**Comment by zhangjing-GitHub-Code** [comment]
还有我在编译过程中有这样的报错，但我已经`apt install *way*l*`了，提示装了libwayland libwayland-proctol libwayland-static xwayland(难道是一些库没装？)(还有一个编译提示没有依赖`libdrm_nouveau`，但libdrm已安装，直接装libdrm_nouveau找不到
```
[1/245] Compiling C object test...l_xdg_shell_unstable_v6_xml.c.o
FAILED: tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.p/meson-generated_.._test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c.o
ccache cc -Itests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.p -Itests -Iwayland-protocols/tests -I/data/data/com.termux/files/usr/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -std=c99 -pedantic -Wall -Werror -MD -MQ tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.p/meson-generated_.._test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c.o -MF tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.p/meson-generated_.._test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c.o.d -o tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.p/meson-generated_.._test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c.o -c tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c
In file included from tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c:1:
/home/dir/tests/xdg-shell-unstable-v6-client.h:444:2: error: implicit declaration of function 'wl_proxy_marshal_flags' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        wl_proxy_marshal_flags((struct wl_proxy *) zxdg_shell_v6,
        ^
/home/dir/tests/xdg-shell-unstable-v6-client.h:444:2: note: did you mean 'wl_proxy_marshal_array'?
/data/data/com.termux/files/usr/include/wayland-client-core.h:129:1: note: 'wl_proxy_marshal_array' declared here
wl_proxy_marshal_array(struct wl_proxy *p, uint32_t opcode,
^
In file included from tests/test-build-pedantic-unstable_xdg_shell_xdg_shell_unstable_v6_xml.c:1:
/home/dir/tests/xdg-shell-unstable-v6-client.h:445:91: error: use of undeclared identifier 'WL_MARSHAL_FLAG_DESTROY'
                         ZXDG_SHELL_V6_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zxdg_shell_v6), WL_MARSHAL_FLAG_DESTROY);
```

**Comment by Xunflash** [comment]
请问如何用chroot来运行呢？参考了这两个链接，可惜都有报错https://github.com/termux/termux-x11/issues/45

https://forum.xda-developers.com/t/guide-running-linux-on-android-with-3d-acceleration-opengl-root-required.4093343/

dbus[4421]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/tmp/" is owned by uid 0, not our uid 1001
/bin/startxfce4: X server already running on display 127.0.0.1:0
xrdb: Connection refused
xrdb: Can't open display '127.0.0.1:0'
Environment variable $XAUTHORITY not set, ignoring.
Failed to import environment: Process org.freedesktop.systemd1 exited with status 1
xfce4-session: 无法打开显示：.
输入 ‘xfce4-session --help’ 获取用法。
